### ISSUE TITLE
Ghost dimlets in dungeon chests

### ISSUE THREAD

**Issue by Dijkstra1** [McJty/RFTools#456]
I have been playing on a mod pack that has both RFTools and runic dungeons which is a dungeon dimension therefore lots of dungeon chests, and in some of there are ghost dimlets they show in chest they can be sorted by inventory tweaks I can put them in my inventory, they will not shift click though and when stacked with real dimlets they just disappear they only come it stacks of one, bigger stacks in  dungeon chests are not affected

**Comment by McJty** [comment]
Yes, this has been reported before but I don't think this is a bug in RFTools. I believe runic dungeons is doing something wrong with chest loot. No idea what though

**Comment by Dijkstra1** [comment]
I would have thought they would just use normal dungeon chests like in Minecraft dungeon also if the bug is runic dungeons why is it only affecting your items.

**Comment by McJty** [comment]
I have no clue but my dimlets are generated using standard chest generation hooks

**Comment by Dijkstra1** [comment]
Well I do not know that part of the forge api, so i can not say one way or the other if you are doing something wrong.  Did look up runic dungeons on github just to see if they had one, they do but no code so I can not even look there to see if there if they are doing something wrong. I will admit I do not remember has this problem with dimlets building in your dimension but i would assume that would be a bit different.

**Comment by MysteriousAges** [comment]
Found them occurring in the 1.9 build. Chests inside RFTools Dimensions structures spawn with dimlet pieces (not the realized dimlets) with stack sizes of 0:
http://i.imgur.com/qKyFH7k.png

**Comment by Mohron** [comment]
I also have dimlet parts generating with a stack size of 0. This is in a RFTools dimension and Runic Dungeons is not installed. It is very common and seems to also affect the loot table of the dimlet Parcels as they often drop nothing at all.

Version: rftoolsdim-1.9.4-4.30beta42.jar
![Dimlet Issue](https://s32.postimg.org/8slndf011/RFtools_Dim0_Stacks.png)

**Comment by kayila** [comment]
A work around for this can be putting the ghost stack into an item frame,
then pulling it back out.

**Comment by Mohron** [comment]
For people on my pack/server, you can't pickup the 0 stacks at all so that's not a work around in our case.

**Comment by McJty** [comment]
I cannot reproduce this anymore so it is possible this is fixed

**Comment by xenoflot** [comment]
Sorry to bear bad news, but it's still lurking. I have the same problem both with ghost stacks and the parcels not delivering any goodies when opened. http://i.imgur.com/HdJFw3s.png  I don't have Runic Dungeons installed.

Please let me know if there's any testing I can do to help!

rftoolsdim-1.10-4.30beta47
rftools-1.10-5.14
forge 1.10.2-12.18.1.2064
Mod list http://pastebin.com/QCvXLYkb

**Comment by xenoflot** [comment]
Updated to rftools 5.16 and it's looking OK for me now.

**Comment by Dijkstra1** [comment]
Still happening in rftools-1.10-5.17, rftoolsdim-1.10-4.30beta47, in a new dim (the tab was made before i updated server but not built util it had so all world gen happen on the above versions), sorry if they are not the latest versions of RF tools/dims it what my pack is using. These are dimlet parts that have a stack size if 0 and delete them when oick them up or sort the chest, dimlets them self seem gen ok and dimlet packages.

**Comment by viper2g1** [comment]
I can confirm this also happens with the latest available RFTools..
 RFTools 5.22 and Dimensions beta 49.

No Runic dungeons installed.

**Comment by RealGrep** [comment]
Also still an issue in beta 50, rftools 5.24, mcjtylib 2.1.2. I see those dimlets with red zeros (as above screenshot) all the time in the dimensional shacks. Shift clicking them makes them vanish. No runic dungeons installed. Also not getting anything when I right click with a dimlet parcel, which is the bug that I headed for this issue tracker for. Doesn't seem resolved, so might want to re-open it.

**Comment by McJty** [comment]
If only I could reproduce this....

**Comment by RealGrep** [comment]
hah Yeah, I hate that. Certainly, if you want me to zip up my server directory, mods/configs/world and all, let me know. Would just need a private channel to give you the link to it. I'm sure I can make a temporary channel on my Discord or something, if necessary.

**Comment by McJty** [comment]
Well ideally I would have to be able to reproduce it in my dev env so I can find out what's up. But I'll check it out though

**Comment by RealGrep** [comment]
No Runic Dungeons, but I think that's similar to Roguelike Dungeons. That I do have. Perhaps that's it. Just mentioning it in case the issue stems from there.

**Comment by RealGrep** [comment]
Latest release seems to have fixed the issues. Went on an exploration binge for dimlets, and not seeing the 0 stacks anymore. And the dimlet parcels are delivering their treats, once again. I'll let you know if I find any, but so far, so good. I'm out after travelling 8500 blocks in a desert for dimensional huts, and that's quite a good sample size.

And grats on reaching release! Only serious issue I've found is button doors on those huts. I hate button doors. Why, oh why, did you have to make them button doors?!?  D:  lol

**Comment by RealGrep** [comment]
After tons of exploration in dimensions, I have not seen this bug surface. It's definitely fixed. Button doors still suck, but you can definitely close this one. :)

**Comment by McJty** [comment]
thanks!
